### ISSUE TITLE
Bug: Multiple declarations in for() causes compiler error

### ISSUE THREAD

**Issue by renaun** [RandoriAS/randori-compiler#169]
AS3

``` actionscript
package bug
{
public class BugV
{
    public function BugV() {
        var k:int = 0;
        for (var i:int=0, j:int=10; i<j; ++i)
            k += i * j;
    }
}
}
```

Compiler outputs:
java.lang.RuntimeException: handle() not found org.apache.flex.compiler.internal.tree.as.ContainerNode
    at randori.compiler.internal.visitor.as.ASNodeSwitch.handle(ASNodeSwitch.java:356)
    at randori.compiler.internal.visitor.as.ASNodeHandler.handle(ASNodeHandler.java:86)
    at randori.compiler.internal.visitor.as.BeforeAfterStrategy.handle(BeforeAfterStrategy.java:111)
    at randori.compiler.internal.codegen.as.ASBlockWalker.walk(ASBlockWalker.java:158)
    at randori.compiler.internal.codegen.as.ASEmitter.visitForBody(ASEmitter.java:1182)
    at randori.compiler.internal.codegen.as.ASEmitter.emitForLoop(ASEmitter.java:900)
    at randori.compiler.internal.codegen.as.ASBlockWalker.visitFor(ASBlockWalker.java:355)
    at randori.compiler.internal.codegen.as.ASBlockWalker.visitForLoop(ASBlockWalker.java:341)
    at randori.compiler.internal.visitor.as.ASNodeSwitch.handle(ASNodeSwitch.java:154)
    at randori.compiler.internal.visitor.as.ASNodeHandler.handle(ASNodeHandler.java:86)
    at randori.compiler.internal.visitor.as.BeforeAfterStrategy.handle(BeforeAfterStrategy.java:111)
    at randori.compiler.internal.codegen.as.ASBlockWalker.walk(ASBlockWalker.java:158)
    at randori.compiler.internal.codegen.as.ASEmitter.emitStatement(ASEmitter.java:792)
    at randori.compiler.internal.codegen.as.ASBlockWalker.visitBlock(ASBlockWalker.java:325)
    at randori.compiler.internal.visitor.as.ASNodeSwitch.handle(ASNodeSwitch.java:257)
    at randori.compiler.internal.visitor.as.ASNodeHandler.handle(ASNodeHandler.java:86)
    at randori.compiler.internal.visitor.as.BeforeAfterStrategy.handle(BeforeAfterStrategy.java:111)
    at randori.compiler.internal.codegen.as.ASBlockWalker.walk(ASBlockWalker.java:158)
    at randori.compiler.internal.codegen.as.ASEmitter.emitIf(ASEmitter.java:820)
    at randori.compiler.internal.codegen.as.ASBlockWalker.visitIf(ASBlockWalker.java:333)
    at randori.compiler.internal.visitor.as.ASNodeSwitch.handle(ASNodeSwitch.java:173)
    at randori.compiler.internal.visitor.as.ASNodeHandler.handle(ASNodeHandler.java:86)
    at randori.compiler.internal.visitor.as.BeforeAfterStrategy.handle(BeforeAfterStrategy.java:111)
    at randori.compiler.internal.codegen.as.ASBlockWalker.walk(ASBlockWalker.java:158)
    at randori.compiler.internal.codegen.as.ASEmitter.emitStatement(ASEmitter.java:792)
    at randori.compiler.internal.codegen.as.ASBlockWalker.visitBlock(ASBlockWalker.java:325)
    at randori.compiler.internal.visitor.as.ASNodeSwitch.handle(ASNodeSwitch.java:257)
    at randori.compiler.internal.visitor.as.ASNodeHandler.handle(ASNodeHandler.java:86)
    at randori.compiler.internal.visitor.as.BeforeAfterStrategy.handle(BeforeAfterStrategy.java:111)
    at randori.compiler.internal.codegen.as.ASBlockWalker.walk(ASBlockWalker.java:158)
    at randori.compiler.internal.codegen.js.RandoriEmitter.emitMethodScope(RandoriEmitter.java:391)
    at randori.compiler.internal.codegen.js.RandoriEmitter.emitMethodScope(RandoriEmitter.java:630)
    at randori.compiler.internal.codegen.js.emitter.MethodEmitter.emit(MethodEmitter.java:117)
    at randori.compiler.internal.codegen.js.RandoriEmitter.emitMethod(RandoriEmitter.java:383)
    at randori.compiler.internal.codegen.as.ASBlockWalker.visitFunction(ASBlockWalker.java:264)
    at randori.compiler.internal.visitor.as.ASNodeSwitch.handle(ASNodeSwitch.java:131)
    at randori.compiler.internal.visitor.as.ASNodeHandler.handle(ASNodeHandler.java:86)
    at randori.compiler.internal.visitor.as.BeforeAfterStrategy.handle(BeforeAfterStrategy.java:111)
    at randori.compiler.internal.codegen.as.ASBlockWalker.walk(ASBlockWalker.java:158)
    at randori.compiler.internal.codegen.js.RandoriEmitter.emitClass(RandoriEmitter.java:309)
    at randori.compiler.internal.codegen.as.ASBlockWalker.visitClass(ASBlockWalker.java:234)
    at randori.compiler.internal.visitor.as.ASNodeSwitch.handle(ASNodeSwitch.java:115)
    at randori.compiler.internal.visitor.as.ASNodeHandler.handle(ASNodeHandler.java:86)
    at randori.compiler.internal.visitor.as.BeforeAfterStrategy.handle(BeforeAfterStrategy.java:111)
    at randori.compiler.internal.codegen.as.ASBlockWalker.walk(ASBlockWalker.java:158)
    at randori.compiler.internal.codegen.js.RandoriEmitter.emitPackageContents(RandoriEmitter.java:212)
    at randori.compiler.internal.codegen.as.ASBlockWalker.visitPackage(ASBlockWalker.java:222)
    at randori.compiler.internal.visitor.as.ASNodeSwitch.handle(ASNodeSwitch.java:111)
    at randori.compiler.internal.visitor.as.ASNodeHandler.handle(ASNodeHandler.java:86)
    at randori.compiler.internal.visitor.as.BeforeAfterStrategy.handle(BeforeAfterStrategy.java:111)
    at randori.compiler.internal.codegen.as.ASBlockWalker.walk(ASBlockWalker.java:158)
    at randori.compiler.internal.codegen.as.ASBlockWalker.visitFile(ASBlockWalker.java:185)
    at randori.compiler.internal.visitor.as.ASNodeSwitch.handle(ASNodeSwitch.java:107)
    at randori.compiler.internal.visitor.as.ASNodeHandler.handle(ASNodeHandler.java:86)
    at randori.compiler.internal.visitor.as.BeforeAfterStrategy.handle(BeforeAfterStrategy.java:111)
    at randori.compiler.internal.codegen.as.ASBlockWalker.walk(ASBlockWalker.java:158)
    at randori.compiler.internal.codegen.as.ASBlockWalker.visitCompilationUnit(ASBlockWalker.java:175)
    at randori.compiler.internal.codegen.js.RandoriWriter.writeTo(RandoriWriter.java:84)
    at randori.compiler.internal.driver.model.ApplicationModel.write(ApplicationModel.java:196)
    at randori.compiler.internal.driver.model.ApplicationModel.generate(ApplicationModel.java:131)
    at randori.compiler.internal.driver.RandoriApplication.generate(RandoriApplication.java:189)
    at randori.compiler.internal.driver.RandoriApplication.compile(RandoriApplication.java:97)
    at randori.compiler.internal.projects.RandoriApplicationProject.buildTarget(RandoriApplicationProject.java:116)
    at randori.compiler.internal.projects.RandoriApplicationProject.startCompile(RandoriApplicationProject.java:97)
    at randori.compiler.internal.projects.RandoriProject.compile(RandoriProject.java:237)
    at randori.compiler.clients.Randori.compile(Randori.java:206)
    at randori.compiler.clients.Randori.startCompile(Randori.java:128)
    at randori.compiler.clients.Randori.mainNoExit(Randori.java:92)
    at randori.compiler.clients.Randori.mainNoExit(Randori.java:81)
    at randori.compiler.clients.Randori.staticMainNoExit(Randori.java:75)
    at randori.compiler.clients.Randori.main(Randori.java:64)
Aborted compile in ApplicationModel.generate()

**Comment by teotigraphix** [comment]
commit      ae5e691
